### ISSUE TITLE
UIWidgets 2.0 does not work with DllNotFoundException (Apple Silicon Mac)

### ISSUE THREAD

**Issue by srdw** [Unity-Technologies/com.unity.uiwidgets#147]
_I'm using Google Translate._

### Overview
When I try UIWidgets 2.0 (preview) in my environment, I get the following error.

```
DllNotFoundException: libUIWidgets
Unity.UIWidgets.engine.UIWidgetsPanelWrapper.Destroy () (at Packages / com.unity.uiwidgets / Runtime / engine / UIWidgetsPanelWrapper.cs: 262)
Unity.UIWidgets.engine.UIWidgetsPanel.OnDisable () (at Packages / com.unity.uiwidgets/Runtime/engine/UIWidgetsPanel.cs:214)
```

### What I tried

1. git clone com.unity.uiwidgets
2. In PackageManger of unity, select add local file. select package.json under /com.unity.uiwidgets
3. Open Sample scene (exc CountTest.unity) or reopen editor

I also tried putting the plugin directly under the Packages folder, but I get the same error.

### Expected behavior
-Run without error

### Development environment
Apple Silicon (M1) Mac
Unity 2021.1.5f1

Supplementary information
-Previous UIWidgets 1.5.4-preview.12 works in a similar way.
-There may be some basic oversights due to my lack of knowledge
-Please let me know if there are any necessary steps & please add to the Readme.

Thank you.

**Comment by zhuxingwei** [comment]
Hi, Thanks for your feedback!

This issue might be caused by several reasons, please try to check:
(1) There is a mistake in the readme,  currently UIWidgets is only supported on **Unity 2019.4.26f1c1 (LTS)**. Thanks a lot for helping us to figure this out !
(2) We have not tried UIWidgets on Apple Silicon, therefore it _might_ be not supported on your Mac yet. Could you test on a normal Apple (Intel) If applicable ?
(3) If you just want to see how UIWidgets works, you can open the sample project using UnityHub at `/Samples/UIWidgetsSamples_2019_4/` and open a scene under `/Samples/UIWidgetsSamples_2019_4/Assets/Scene/`. 
(4) If you want to use UIWidgets in your own project, please check `Packages/manifest.json` in your project and ensure that the dependency on uiwidgets is properly set.

**Comment by srdw** [comment]
Hi, Thanks for your reply!

> (1) There is a mistake in the readme, currently UIWidgets is only supported on Unity 2019.4.26f1c1 (LTS). Thanks a lot for helping us to figure this out !
> (3) If you just want to see how UIWidgets works, you can open the sample project using UnityHub at /Samples/UIWidgetsSamples_2019_4/ and open a scene under /Samples/UIWidgetsSamples_2019_4/Assets/Scene/.

I installed the latest Unity 2019.4 series 2019.4.25f1 that can be downloaded from Unity Hub and opened "/ Samples / UIWidgetsSamples_2019_4 /".
Again, a DllNotFoundException occurred.

Need to be Chinese version (c1)?
I am accessing from Japan.


> (2) We have not tried UIWidgets on Apple Silicon, therefore it might be not supported on your Mac yet. Could you test on a normal Apple (Intel) If applicable ?

I don't have an Intel Mac, so I'd like someone to build and report it.

***

By the way, I am making a text-based game that combines the game AI made with Unity and the UI of UIWidgets.

I'm thinking of starting production with UIWidgets 1.5 while waiting for the update.
(I understand there are breaking changes)

**Comment by zhuxingwei** [comment]
(1) Yes, very sorry that UIWidgets is only supported on Chinese version for now :hushed:
(2) Since 2.0 is still in preview, we suggest you to use the latest UIWidgets 1.X for your current production development (for better stability and bug free). We will continue to polish 2.0 in May and you can switch to 2.0 later then (Our in-house connectApp project has already switched from 1.0 to 2.0, which only takes half a month)

Wish you a happy development experience with UIWidgets!

**Comment by srdw** [comment]
I understand.
This issue is closed and okay.

Implement in stable version.
I'm looking forward to using 2.0!

Thank you for your quick reply.
