### ISSUE TITLE
Unity crashing while importing

### ISSUE THREAD

**Issue by piotrszpruta** [Unity-Technologies/com.unity.uiwidgets#164]
I tried importing package downloaded from github, I followed instructions and it crashed half way, now unity wont open this project
Unity 2019.4.26f1
Windows
New project

![image](https://user-images.githubusercontent.com/38475451/118859192-41211300-b8da-11eb-807e-20876a9ca0ec.png)

Thats error log which unity generated
[error.log](https://github.com/Unity-Technologies/com.unity.uiwidgets/files/6510729/error.log)

**Comment by zhuxingwei** [comment]
Hi, Thanks for the feedback!

The latest UIWidgets master (i.e., UIWidgets 2.0) is only supported on Unity 2019.4.26f1c1 ( Please note the "c1" suffix which means this is a specific version released in China). You can get the Editor from this url (https://unity.cn/releases). 

If you still want to use Unity 2019.4.26f1, please use the uiwidgets_1.0 branch instead.

**Comment by piotrszpruta** [comment]
@zhuxingwei thanks, I didn't know that there's much differences between China version and lets say global. Might I ask if there's something I'm missing while using uiwidgets_1.0 branch?

**Comment by zhuxingwei** [comment]
Generally, China version is almost the same as the "global version" with additional China market specific features, including uiwidgets. We will eventually make uiwidgets available for all Unity editors, though there is still a long way to go :-）

If you are using uiwidgets_1.0, 2019.4.26f1 should be ok.  

Although uiwidgets 2.0 is very different to uiwidgets 1.0 in the technique perspective, they are nearly the same to developers, except for: (1) you need a different code pattern to attach a uiwidget app with a gameobject/editorwindow;  (2) some apis might changes a bit since in uiwidgets 2.0 we upgrade the framework to match that of flutter 1.17.5 (while uiwidgets 1.0 matches 1.5.4). 

You can find the user tutorial for uiwidgets_1.0 in the readme file of the corresponding branch. Feel free to create issues if you have other questions. Thanks !

**Comment by piotrszpruta** [comment]
Sadly I've got same result with uiwidgets_1.0 and Unity 2019.4.26.f1. I don't know if this log helps.

[error.log](https://github.com/Unity-Technologies/com.unity.uiwidgets/files/6513637/error.log)

**Comment by zhuxingwei** [comment]
It seems you are still using uiwidgets 2.0.

Please make sure that "git branch -vv" under the uiwidgets package shows that your current branch status is:
```
....
* uiwidgets_1.0       395bf4c3 [origin/uiwidgets_1.0] Merge pull request #161 from Unity-Technologies/issue_1.0/editor_window_color_issue
....
```

If it is, then re-open Unity may solve your problem

**Comment by piotrszpruta** [comment]
Sorry yes, you're right somehow I was still using 2.0. Works now thanks!

**Comment by baoxiehao** [comment]
2020.3.25f1 crash too

**Comment by zhuxingwei** [comment]
Hi thanks for the report !

If you are using the master branch or UIWidgets 2.0 in specific, please open UIWidgets project with the Unity China version. Please read our [FAQ](https://github.com/Unity-Technologies/com.unity.uiwidgets#faq) for further information.
