### ISSUE TITLE
安卓打包不显示

### ISSUE THREAD

**Issue by Rocktome** [Unity-Technologies/com.unity.uiwidgets#227]
安卓打包apk，uiwidgets不显示,截图是插件示例场景
![Screenshot_20210813_111801_com DefaultCompany UIWidgetsSamples](https://user-images.githubusercontent.com/34135314/129300637-b0fd1529-53bb-405c-a904-5c2d514f2700.jpg)

手机型号是honor10,红米k20pro
unity版本：2019.4.27f1c
电脑windows10
uiwidgets版本：2.0.3-preview.1

**Comment by zhuxingwei** [comment]
Hi, thanks for the reporting !

Please check the following stuff:
(1) Is the UIWidgets panel shows up properly on your Unity Editor?
(2) What is the target architecture? UIWidgets 2.0.3 only support armv7 on Android. (The latest master branch will support arm64 though)
(3) What GraphicDevice are you using? UIWidgets 2.0.3 only support OpenGLES on Android.
(4) Is there any error log shown up in  the logcat output? If there is any, please paste it here so that we can dig inside for useful information. 

Thanks for your help!

**Comment by Rocktome** [comment]
1.我用的是最新的master
2.我的编辑器显示是正常的
![image](https://user-images.githubusercontent.com/34135314/129503166-c2da4949-754e-41a0-b939-574fe10e538c.png)

3.目标架构

![image](https://user-images.githubusercontent.com/34135314/129503236-97ac123a-3693-4de1-a21e-ea0bcc921d26.png)

4.GraphicDevice

![image](https://user-images.githubusercontent.com/34135314/129503262-a81b58c7-73dd-4603-9069-c321b1b0e304.png)

5.打印输出是正常的

![image](https://user-images.githubusercontent.com/34135314/129503293-8b1159bf-cbb9-41ca-b7c4-d5bce0564d3a.png)

**Comment by guanghuispark** [comment]
Hi, @Rocktome , After our test, 2019.4.28f1c1 works fine，you can upgrade unity version to 2019.4.28f1c1. By the way,  we recommend switching to the master branch.

**Comment by guanghuispark** [comment]
Currently we are still locating the problem about 2019.4.27f1c1, and we will notify you when it is fixed.

**Comment by Rocktome** [comment]
@guanghuispark 我运行起来了，多谢了，期待插件越做越好
