### ISSUE TITLE
Flutter build inside Unity

### ISSUE THREAD

**Issue by pajama** [Unity-Technologies/com.unity.uiwidgets#255]
Given that UIWidgets includes a full flutter engine, is it possible to render a flutter app inside Unity? Or would we need to rebuild in c#? My goal is to have a floating flutter panel inside a 3d environment. Thanks!

**Comment by zhuxingwei** [comment]
Hi Thanks a lot for the question!

Yes, it is possible to render a "flutter app" in Unity with UIWidgets: To do so, all you need is to convert the dart codes in your flutter app into C#. According to our experience, it should be easy since C# and dart are very similar to each other.

To start with, you can first try our [Samples](https://github.com/Unity-Technologies/com.unity.uiwidgets/tree/master/Samples/UIWidgetsSamples_2019_4) which are shipped together with the uiwidgets package. 

To achieve your goal, please have a look at this [repo](https://plastichub.unity.cn/unity-tech-cn/awesome-uiwidgets): I think it is just want you need :-)

**Comment by pajama** [comment]
@zhuxingwei thanks for the links!

I played around with the samples. Very exciting stuff! I also dug around the awesome-uiwidgets repo a bit, but I'm not sure how relevant it is for my use case. Is there something in there in particular I should check out? 

The c# api seems to have decent coverage of the original flutter apis, but I still very much want to build my widgets in dart so I can use the hot reload tooling. It's not hard to manually convert from dart to c#, but in an environment where we are constantly iterating, that can only take us so far. Do you know of any good dart to c# translator plugins that can handle the api differences?
