### ISSUE TITLE
Can't open projects with Unity Hub cn. Trying to test UIWidgets 2.0.2

### ISSUE THREAD

**Issue by pajama** [Unity-Technologies/com.unity.uiwidgets#257]
I decided to give ui widgets 2 a try with the proper supported cn version. I was only able to install the cn version by first downloading the Unity Hub cn version.
 
In hub, 
-the "Add" button does nothing. 
-new project window doesn't let me select a location. Any project name says "Path already exists"
![image](https://user-images.githubusercontent.com/2224105/137415417-0c79b9fe-3f36-4758-98c8-8851f6c282b3.png)

-opening the cn version of the editor directly, just launches me back to the hub.

Thanks for the help!

**Comment by zhuxingwei** [comment]
Hi sorry for the late response !

This issue might be caused by the inconsistency between you Unity Hub and the cached configurations, please try the following steps to fix it:

(1) Close your Unity Hub cn
(2) Delete all the cached files under this path `C:\Users\xxxx\AppData\Roaming\UnityHub` on Windows
(3) Try the upgrade Unity Hub cn to the latest version
(4) Reopen Unity Hub cn

Feel free to contact us if you have any other question!

**Comment by pajama** [comment]
Clearing the cache did the trick. Thanks!
