### ISSUE TITLE
[Question] Does UIWidgets support Flutter widgets that are from Flutter plugins, i.e. not official builtin widgets?

### ISSUE THREAD

**Issue by baoxiehao** [Unity-Technologies/com.unity.uiwidgets#291]

**Comment by zhuxingwei** [comment]
Yes, you can translate any flutter widgets from dart to C# and then use them directly in UIWidgets.

**Comment by baoxiehao** [comment]
> Yes, you can translate any flutter widgets from dart to C# and then use them directly in UIWidgets.

So any documentation for that？I guess need to translate those plugin widgets as the UIWidgets do, any other requirements?

**Comment by zhuxingwei** [comment]
no other requirements. 

For the way to translate dart to C#, sorry that we don't have any document yet. However, C# and dart are very similar in grammar, it won't be hard to make the translation. Moreover, since most of UIWidgets framework C# codes are translated from flutter framework which is written in dart, it should be also useful for you as a reference.
