### ISSUE TITLE
worldspace 模式下的透明问题

### ISSUE THREAD

**Issue by tomcatter** [Unity-Technologies/com.unity.uiwidgets#299]
我将`UIWidgetsPanel`挂载到的`RawImage`所属的`canvas`设置为`World Space`模式。`UIWidgets`界面的背景颜色都设置为黑色，整个场景使用URP进行渲染，发现UIWidges并没有纯黑，而是有一些透明，如下图：
![0220115221923](https://user-images.githubusercontent.com/7018011/149624942-d90df603-6d6e-4f07-aa24-a6afe5773c77.png)

`UIWidgets`背后的物体可见，造成这种现象的原因可能是什么？

**Comment by zhuxingwei** [comment]
Hi Thanks for the issue reporting !

We are sorry that we cannot reproduce this issue in our repo (we mainly tested on our world space ui demos in https://plastichub.unity.cn/unity-tech-cn/awesome-uiwidgets). 

From the screenshot you provided, I can see that only some of the game objects behind the UI are incorrectly visible. For example, only the grid lines on the floor are visible but the railings are not. So it is more likely caused by wrong settings on these game objects instead of UIWidgets. However, I cannot tell which part might go wrong given only a screenshot.

You can send us a minimal demo that reproduces this error If needed (via Google drive or anything you have in hands), we can try to figure it out then.

**Comment by tomcatter** [comment]
@zhuxingwei 我找到解决的办法了，修改`Canvas`的`Order in Layer`，正确显示了
