### ISSUE TITLE
Why is this only for the China version of unity ?

### ISSUE THREAD

**Issue by Kulgann** [Unity-Technologies/com.unity.uiwidgets#300]
I just dont understand how is it compatible with only the Chinese version. As a non-Chinese developer how do I use it ?

**Comment by zhuxingwei** [comment]
Hi thanks for the feedback!

The reason why UIWidgets 2.0 is only compatible with Chinese version can be found in the 3rd question of our [FAQ](https://github.com/Unity-Technologies/com.unity.uiwidgets#faq).

If you want to used UIWidgets 2.0, a straight-forward way is to just download the Unity Hub of Chinese version (open our url at https://unity.cn/releases and press the green button with label "下载Unity Hub") and then use it to download the latest Unity of Chinese version.

**Comment by Kulgann** [comment]
> Hi thanks for the feedback!
> 
> The reason why UIWidgets 2.0 is only compatible with Chinese version can be found in the 3rd question of our [FAQ](https://github.com/Unity-Technologies/com.unity.uiwidgets#faq).
> 
> If you want to used UIWidgets 2.0, a straight-forward way is to just download the Unity Hub of Chinese version (open our url at https://unity.cn/releases and press the green button with label "下载Unity Hub") and then use it to download the latest Unity of Chinese version.

Are there plans to make this a part of all unity versions in the future?

**Comment by zhuxingwei** [comment]
Yes we do have a long-term plan to accomplish this. 

But please also be aware of that it is **not** part of our current roadmap though since it still requires many discussions among people besides the dev team.

**Comment by PrestigeDevop** [comment]
why does it use skia renderer doses it have  a warrper like skiaSharp  ? 
isn't Tiny project suppose to be faster due to DOTS? or because this project was build from the ground up to use native headers ?

> Yes we do have a long-term plan to accomplish this.
> 
> But please also be aware of that it is **not** part of our current roadmap though since it still requires many discussions among people besides the dev team.

**Comment by zhuxingwei** [comment]
Hi Thanks for your question !

(1) Yes, UIWidgets has a wrapper layer upon flutter engine (you can find it easily under the /engine/ folder). We use flutter and skia directly so that the rendering result is exactly the same as in flutter. btw, in UIWidgets 1.0 we choose to use Unity GraphicsAPIs to mimic the rendering part but the result turns out to be not perfect.

(2) Though we are really interesting in leveraging DOTS to accelerate UIWidgets, it is still far from something we can talk about deeper. So far, UIWidgets still mainly focuses on the support for non-DOTS Unity apps.

**Comment by PrestigeDevop** [comment]
> Hi Thanks for your question !
> 
> (1) Yes, UIWidgets has a wrapper layer upon flutter engine (you can find it easily under the /engine/ folder). We use flutter and skia directly so that the rendering result is exactly the same as in flutter. btw, in UIWidgets 1.0 we choose to use Unity GraphicsAPIs to mimic the rendering part but the result turns out to be not perfect.
> 
> (2) Though we are really interesting in leveraging DOTS to accelerate UIWidgets, it is still far from something we can talk about deeper. So far, UIWidgets still mainly focuses on the support for non-DOTS Unity apps.

 Thanks for answering my question, could you confirm if this project would be available for LTS version , besides that I want to know Project Tiny use some of API library similar to this repo i.e bee .net core namespace ( not direct reference)  I would like to know more about this library, the project Tiny required a vs 2019 c++ workloads , I've installed vs 2022 workloads but it doesn't detect it do you think I could register system environment variable as workaround any details are welcomed

I appreciate your help thanks,

**Comment by PrestigeDevop** [comment]
> Hi Thanks for the reply !
> 
> (1) Yes, we are pretty sure that UIWidgets 2.0 will continue to support at least 2019, 2020 LTS (CN version), and we are also beginning to work on support 2021 LTS.
> 
> (2) `bee` is a special building toolkit developed and used in Unity internally only. As to project Tiny, are you referring to https://forum.unity.com/forums/project-tiny.151/ ? if it is, I don't see anything inside this project which requires C++ environments. btw, as to my knowledge, this project is currently suspended and not product ready yet.

It's mentioned in the documentation on  https://github.com/Unity-Technologies/ProjectTinySamples  
I open an issue there as well...

I know it's not updated I want to make some native apps  it seems both projects probably yse the same building tools you mentioned .
Idk which one I should use , I tried project tiny because it has asm.js build option.


so if I installed Chinese version and change the language to English this repo will work ? idk what makes Chinese version required but I hope I don't have to use Google translate alot 😅

**Comment by zhuxingwei** [comment]
(1) Yes, `bee` is the in-house build systems used in many internal projects of Unity besides UIWidgets. As for more detailed information on this tool, you may want to ask somewhere in our forum (https://forum.unity.com/forums) where you can reach out to my colleagues from the build system team directly.

(2) Yes, you can get the currently supported LTS versions in our latest Readme file and download the Editors from https://unity.cn/, which may be the only place where you need Google translate. The CN Editors look nearly the same as the non-CN Editors.
