### ISSUE TITLE
[...] expected x64 architecture, but was Unknown

### ISSUE THREAD

**Issue by piotrszpruta** [Unity-Technologies/com.unity.uiwidgets#303]
After importing uiWidgets 2.0.4 into unity 2020.3.26f1c1 it shows this error.

![image](https://user-images.githubusercontent.com/38475451/151454434-364a6bef-5ea8-47de-bf90-d820bf4cc795.png)

**Comment by zhuxingwei** [comment]
Hi Thanks for the reporting !

It seems that Unity cannot find the proper UIWidgets library on your PC. Since the Unity version looks to be fine, please check whether the library is at the proper place and complete. You can find a detailed checklist in our [FAQ](https://github.com/Unity-Technologies/com.unity.uiwidgets#faq) (question 2)
