### ISSUE TITLE
一个场景中同时挂载多个继承自UIWidgetsPanel的脚本，TextFormField 对输入事件响应的问题

### ISSUE THREAD

**Issue by tomcatter** [Unity-Technologies/com.unity.uiwidgets#304]
我现在的使用是这样的，有多个继承自`UIWidgetsPanel`的脚本，分别挂载在`overlay`模式和`world space`模式下的`canvas`里。在其中的一个界面里有`TextFormField`的一个输入框。

出现的问题：输入时会重复显示按键内容

排查过程：断点`UIWidgetsPanel`类中的`Input_OnGUI`函数，发现有多个相同的输入事件插入到`PointerEventConverter.KeyEvent`这个队列中，导致内容重复，观察插入的事件数量和存在的`UIWidgetsPanel`数量一致，减少`UIWidgetsPanel`的数量，重复的次数也随着减少，当只有一个`UIWidgetsPanel`时，内容不再重复。

**Comment by zhuxingwei** [comment]
Hi Thanks a lot for the feedback!

The root cause of this issue is that the `EventSystem` will dispatch a `KeyEvent` to all UIWidgets panels by default therefore it will be processed for multiple times by every panel.

We will investigate this issue and make a PR to fix it later. Thanks for your great help and we will let you know on this thread when the corresponding PR lands.

**Comment by zhuxingwei** [comment]
fixed in #308

**Comment by tomcatter** [comment]
已验证，问题修复
