### ISSUE TITLE
FileImage可否增加支持自定义路径？

### ISSUE THREAD

**Issue by tomcatter** [Unity-Technologies/com.unity.uiwidgets#314]
现在的UI资源都是从`Application.streamingAssetsPath`中进行加载，能否支持从其他路径进行加载，比如在`android`平台，我的资源先下载到`data/data/`目录下面，这样就能动态更新资源。希望能提供一个更灵活的加载路径接口。

**Comment by zhuxingwei** [comment]
Hi Thanks for the feedback!

Yes, this feature looks straight-forward and reasonable to me. We will put it into our recent dev plan and make it done asap.

**Comment by zhuxingwei** [comment]
Sorry for the delayed PR caused by Covid issues in Shanghai. In #316 we proposed a simple solution to support more flexible image file path configuration.

We are planning to land it on `master` later this week after some internal reviews. We will also be very glad to hear from your feedbacks too, Thanks! @tomcatter

**Comment by zhuxingwei** [comment]
fix lands in #316
